#Multiplier for the max stack size for all items placed in a nether chest.
#The stack size of already damaged items cannot be increased.
#Default Value: 8
#Range: 1 ~ 32
stack_size_multiplier = 8
#Strength of the explosion when a nether chest is trying to be opened in the nether dimension.
#Default Value: 0
#Range: > -2147483648
nether_explosion_strength = 0
